#-------------------------------
# General Site Settings
baseURL = "https://seosaurus.fr"
languageCode = "fr"
title = "SEOsaurus"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 5


[params]
  logo = "" # You can add own logo. For example "/images/tlem_logo.png".
  description = "SEOsaurus, webmarketing consulting."
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
## Tu te reconnais dans l'une des affirmations suivantes ? ü§î

- üí≠¬´ Je suis en train de lancer mon entreprise ¬ª
- üí≠¬´ Mon objectif est d'accro√Ætre ma visibilit√© et d'attirer des (nouveaux) clients ¬ª
- üí≠¬´ J‚Äôai des besoins (ponctuels) en infographie et cr√©ations de contenus pour mes r√©seaux sociaux ou mon site web ¬ª
- üí≠¬´ Mon souhait est de renforcer ma pr√©sence en ligne pour b√¢tir et fid√©liser mon audience ¬ª

Si oui, alors j'ai une bonne nouvelle pour toi, tu es au bon endroit ! ü¶ï

## Ce que je peux faire pour toi :

- üåã **Strat√©gie de communication | image de marque**

Je t'accompagne dans la d√©finition de ta strat√©gie de communication en ligne, choisir tes canaux, pour atteindre tes objectifs.
Je t'aide aussi dans la cr√©ation de ton identit√© visuelle et r√©dactionnelle avec des templates, des banni√®res, ou miniatures.

- ü¶¥ **R√©seaux sociaux / Community management**

Facebook, Instagram, LinkedIn, Mastodon, Discord... Je m'occupe de tes r√©seaux sociaux et tu ne t'occupes de rien !

- üåø **R√©f√©rencement naturel**

Si tu ne travailles pas ton r√©f√©rencement naturel, tu ne peux pas √™tre visible et remonter dans les moteurs de recherche.
Je cr√©e, r√©dige, optimise et g√®re tous tes contenus pour t'aider √† gagner en visibilit√© et en trafic. Que ce soit pour ton blog, ta newsletter, tes r√©seaux sociaux ou ta fiche Google My Business, SEOsaurus s'occupe de tout.
Petit √† petit, gr√¢ce √† ses comp√©tences, ton site web √©volue comme un ≈ìuf de dinosaure, et bient√¥t, un petit pt√©rodactyle y √©clot, te propulsant en premi√®re page de Google ! ü¶ñ

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Mes services"
    url = "/messervices/"
    weight = 2
    hasChildren = true

  [[menu.main]]
    parent = "Mes services"
    name = "R√©f√©rencement SEO"
    url = "/referencementseo/"
    weight = 1

  [[menu.main]]
    parent = "Mes services"
    name = "Strat√©gie de communication"
    url = "/strat√©giedecommunication/"
    weight = 1
    
  [[menu.main]]
    parent = "Mes services"
    name = "Cr√©ation de contenu (prints)"
    url = "/creationdecontenu/"
    weight = 1
    
  [[menu.main]]
    parent = "Mes services"
    name = "Community management"
    url = "/communitymanagement/"
    weight = 1
    
  [[menu.main]]
    name = "R√©alisations"
    url = "/r√©alisations/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5


  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Jason Hill"
    author__bio = "Hi, I'm Jason ‚Äì Graphic Designer. I'm a creative and curious person who has a lot of experience and fond moments working with design, websites, and marketing."
    author__avatar = "https://via.placeholder.com/400x400"

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "ion-logo-youtube"
  #   name = "Youtube"
  #   link = "https://youtube.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Hey everyone, I‚Äôm Jason Hill"
    hero__description = "Hi, I'm Jason ‚Äì Graphic Designer. I'm a creative and curious person who has a lot of experience and fond moments working with design, websites, and marketing."
    hero__image = "https://via.placeholder.com/1200x800"


    #-------------------------------
    # Logos Settings
    [params.logos]
      enable = true
      logos__title = "I‚Äôve worked with some great —Åompanies"

    [[params.logo_item]]
      name = "Google"
      link = "https://www.google.com/"
      image = "/images/google.svg"

    [[params.logo_item]]
      name = "Spotify"
      link = "https://www.spotify.com/"
      image = "/images/spotify.svg"

    [[params.logo_item]]
      name = "Pinterest"
      link = "https://www.pinterest.com/"
      image = "/images/pinterest.svg"

    [[params.logo_item]]
      name = "Netlify"
      link = "https://www.netlify.com/"
      image = "/images/netlify.svg"

    [[params.logo_item]]
      name = "Apple"
      link = "https://www.apple.com/"
      image = "/images/apple.svg"

    [[params.logo_item]]
      name = "Adobe"
      link = "https://www.adobe.com/"
      image = "/images/adobe.svg"


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Subscribe" # Add your button text


  #-------------------------------
  # Work Settings
  [params.work]
    enable = true
    work__title= "Work"
    work__description= "I shows only the best websites and portfolios built completely with passion, simplicity & creativity!"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "Clients"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Hanna Septimus"
    image = "https://via.placeholder.com/400x400"
    designation = "Product Designer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Carla Rosser"
    image = "https://via.placeholder.com/400x400"
    designation = "Statistician"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Maria Curtis"
    image = "https://via.placeholder.com/400x400"
    designation = "Team Lead"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Carter Bergson"
    image = "https://via.placeholder.com/400x400"
    designation = "CEO, Founder"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Jordyn Franci"
    image = "https://via.placeholder.com/400x400"
    designation = "Personal Trainer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Mira Carder"
    image = "https://via.placeholder.com/400x400"
    designation = "Data Scientist"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Madelyn Herwitz"
    image = "https://via.placeholder.com/400x400"
    designation = "Frontend Engineer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Anika Schleifer"
    image = "https://via.placeholder.com/400x400"
    designation = "Fitness Director"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Wilson Dorwart"
    image = "https://via.placeholder.com/400x400"
    designation = "Financial Manager"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Writing"
    blog__description = ""


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__background__image = "https://via.placeholder.com/1920x1080"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "your@email.com" # Add your form_id

    # NOTE
    # Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
